// 이 파일은 config/exchange-support.yaml에서 자동 생성됩니다.
package support

import "github.com/proven-trade/cex-sdk/model"

var catalogData = []ProductSupport{
	{
		Exchange: model.ExchangeID("binance"), DisplayName: "Binance", Tier: "P0",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BINANCE_WEBSOCKET.md"},
	},
	{
		Exchange: model.ExchangeID("binance"), DisplayName: "Binance", Tier: "P0",
		Product: ProductID("usdm_futures"), ProductName: "USDⓈ-M Futures",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BINANCE_USDM.md"},
	},
	{
		Exchange: model.ExchangeID("bitget"), DisplayName: "Bitget", Tier: "P0",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BITGET.md"},
	},
	{
		Exchange: model.ExchangeID("bitget"), DisplayName: "Bitget", Tier: "P0",
		Product: ProductID("usdtm_futures"), ProductName: "USDT-M Futures",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BITGET.md"},
	},
	{
		Exchange: model.ExchangeID("upbit"), DisplayName: "Upbit", Tier: "P0",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/UPBIT.md"},
	},
	{
		Exchange: model.ExchangeID("bybit"), DisplayName: "Bybit", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BYBIT.md"},
	},
	{
		Exchange: model.ExchangeID("bybit"), DisplayName: "Bybit", Tier: "P1",
		Product: ProductID("linear_perpetual"), ProductName: "Linear Perpetual",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BYBIT.md"},
	},
	{
		Exchange: model.ExchangeID("okx"), DisplayName: "OKX", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/OKX.md"},
	},
	{
		Exchange: model.ExchangeID("okx"), DisplayName: "OKX", Tier: "P1",
		Product: ProductID("swap"), ProductName: "SWAP",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/OKX.md"},
	},
	{
		Exchange: model.ExchangeID("coinbase"), DisplayName: "Coinbase Advanced", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/COINBASE.md"},
	},
	{
		Exchange: model.ExchangeID("kraken"), DisplayName: "Kraken", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/KRAKEN.md"},
	},
	{
		Exchange: model.ExchangeID("kraken"), DisplayName: "Kraken", Tier: "P1",
		Product: ProductID("futures"), ProductName: "Futures",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/KRAKEN_FUTURES.md"},
	},
	{
		Exchange: model.ExchangeID("bithumb"), DisplayName: "Bithumb", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/BITHUMB.md"},
	},
	{
		Exchange: model.ExchangeID("coinone"), DisplayName: "Coinone", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/COINONE.md"},
	},
	{
		Exchange: model.ExchangeID("korbit"), DisplayName: "Korbit", Tier: "P1",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/KORBIT.md"},
	},
	{
		Exchange: model.ExchangeID("kucoin"), DisplayName: "KuCoin", Tier: "P2",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/KUCOIN.md"},
	},
	{
		Exchange: model.ExchangeID("kucoin"), DisplayName: "KuCoin", Tier: "P2",
		Product: ProductID("futures"), ProductName: "Futures",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("planned"), LiveTradeSmoke: Status("planned"),
		Docs: []string{"docs/exchanges/KUCOIN_FUTURES.md"},
	},
	{
		Exchange: model.ExchangeID("gateio"), DisplayName: "Gate.io", Tier: "P2",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/GATEIO.md"},
	},
	{
		Exchange: model.ExchangeID("gateio"), DisplayName: "Gate.io", Tier: "P2",
		Product: ProductID("futures"), ProductName: "Futures",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("not_applicable"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("planned"), LiveTradeSmoke: Status("planned"),
		Docs: []string{"docs/exchanges/GATEIO_FUTURES.md"},
	},
	{
		Exchange: model.ExchangeID("mexc"), DisplayName: "MEXC", Tier: "P3",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/MEXC.md"},
	},
	{
		Exchange: model.ExchangeID("htx"), DisplayName: "HTX", Tier: "P4",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/HTX.md"},
	},
	{
		Exchange: model.ExchangeID("cryptocom"), DisplayName: "Crypto.com", Tier: "P4",
		Product: ProductID("spot"), ProductName: "Spot",
		REST: Status("experimental"), WebSocketPublic: Status("experimental"), WebSocketPrivate: Status("experimental"),
		Unified: Status("experimental"), AutomatedTests: Status("implemented"),
		LiveReadSmoke: Status("pending"), LiveTradeSmoke: Status("pending"),
		Docs: []string{"docs/exchanges/CRYPTOCOM.md"},
	},
}
